favorite_locations = ["island", "greece", "france", "england", "japanese"]

print(favorite_locations)
print(sorted(favorite_locations))
print(favorite_locations)
print(sorted(favorite_locations, reverse=True))
print(favorite_locations)
favorite_locations.reverse()
print(favorite_locations)
favorite_locations.reverse()
print(favorite_locations)
favorite_locations.sort()
print(favorite_locations)
favorite_locations.sort(reverse=True)
print(favorite_locations)